BarberShop.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace BarberShop.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BarberShop.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BarberShop.Bll.Interfaces;
using BarberShop.Bll.DTOs;

namespace BarberShop.Web.Pages
{
    public class IndexModel : PageModel
    {
        public IBarberService BarberService { get; }
        public IndexModel(IBarberService barberService)
        {
            BarberService = barberService;
        }

        public IEnumerable<BarberDTO> Barbers { get; set; }

        public async Task OnGetAsync()
        {
            var barbers = await BarberService.GetBarbersAsync();
            Barbers = barbers.OrderBy(d => d.Id).Take(4);
        }
    }
}

BarberShop.Web/ViewComponents/BarberCardViewComponent.cs
using BarberShop.Bll.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BarberShop.Web.ViewComponents
{
    public class BarberCardViewComponent : ViewComponent
    {
        public IBarberService BarberService { get; }
        public BarberCardViewComponent(IBarberService barberService)
        {
            BarberService = barberService;
        }

        public class BarberCard
        {
            public int BarberId { get; set; }
            public string BarberName { get; set; }
            public string PhotoPath { get; set; }
            public string PublicDescription { get; set; }
        }

        public IViewComponentResult Invoke(int barberId, string barberName, string photoPath, string publicDescription)
        {
            var barberCard = new BarberCard
            {
                BarberId = barberId,
                BarberName = barberName,
                PhotoPath = photoPath,
                PublicDescription = publicDescription
            };

            return View(barberCard);
        }
    }
}

BarberShop.Web/ViewComponents/ServiceTypesViewComponent.cs
using BarberShop.Bll.DTOs;
using BarberShop.Bll.Interfaces;
using BarberShop.Web.Enums;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BarberShop.Web.ViewComponents
{
    public class ServiceTypesViewComponent : ViewComponent
    {
        public IServiceTypeService ServiceTypeService { get; }
        public ServiceTypesViewComponent(IServiceTypeService serviceTypeService)
        {
            ServiceTypeService = serviceTypeService;
        }

        public class DisplayServiceTypes
        {
            public DisplayType DisplayType { get; set; }
            public IList<ServiceTypeDTO> ServiceTypes { get; set; }
        }

        public async Task<IViewComponentResult> InvokeAsync(DisplayType displayType)
        {
            var displayServiceType = new DisplayServiceTypes { DisplayType = displayType };

            displayServiceType.ServiceTypes = await ServiceTypeService.GetServiceTypesAsync();

            return View(displayServiceType);
        }
    }
}

BarberShop.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<main>
    <div class="container">
        <div class="row">

            <div class="col-md-6">
                <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="~/img/slide1.jpg" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="~/img/slide2.jpg" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="~/img/slide3.jpg" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>

            <div class="col-md-6 text-center m-auto">
                <div class="mt-4">
                    <h3 class="pb-1">Barber Shop</h3>
                    <p>9012 Győr, Vadvirág utca 1.</p>
                    <p>tel.: +36 70 111 2233</p>
                </div>
            </div>

        </div>
    </div>

    <div class="mt-4">
        <h3>Borbélyüzletünkről</h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at sapien sed nisl elementum ullamcorper. Praesent in ligula nisl.
            Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum viverra et arcu non lacinia.
            Praesent euismod sagittis arcu, nec interdum dui bibendum elementum. Suspendisse ullamcorper sit amet turpis et auctor. Cras convallis posuere
            magna id elementum.
        </p>
        <p>
            Pellentesque commodo ipsum quis dui imperdiet suscipit. Vivamus vitae odio odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            In hac habitasse platea dictumst. Proin in dolor metus. Phasellus accumsan augue ut blandit efficitur. Nullam condimentum semper condimentum.
            Donec bibendum accumsan tortor ultricies mollis. Nullam convallis libero id condimentum euismod. Proin eu eros accumsan felis facilisis luctus.
            Ut enim ante, ultrices ac libero eget, suscipit pharetra nibh. Nullam bibendum sem at lectus posuere, ac eleifend leo blandit. Ut pellentesque,
            mi sed consectetur fermentum, nisl nulla tempor neque, non facilisis turpis mauris nec tortor.
        </p>
    </div>

    <div class="barbercard">
        <div id="carouselBarbersIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                @for (int i = 0; i < 3 && i < Model.Barbers.Count(); i++)
                {
                    <li data target="#carouselBarbersIndicators" data-slide-to="@i" class="@(i == 0 ? "active" : "")"></li>
                }
            </ol>
            <div class="carousel-inner">
                @{
                    var first = true;
                    foreach (var barber in Model.Barbers)
                    {
                        <div class="carousel-item @(first ? "active" : "")">
                            <div class="container">
                                <div class="row">

                                    <vc:barber-card barber-id="@barber.Id" barber-name="@barber.Name" photo-path="@barber.PhotoPath" public-description="@barber.PublicDescription"></vc:barber-card>

                                </div>
                            </div>
                        </div>

                        first = false;
                    }
                }
            </div>
            <a class="carousel-control-prev" href="#carouselBarbersIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselBarbersIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <vc:service-types display-type="@Enums.DisplayType.User"></vc:service-types>

</main>